services:
  backend:
    build:
      context: ./Backend
    container_name: hospital-backend
    ports:
      - "4000:4000"
    env_file:
      - ./Backend/config/config.env
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    container_name: hospital-frontend
    ports:
      - "5173:5173"

  dashboard:
    build:
      context: ./dashboard
    container_name: hospital-dashboard
    ports:
      - "5174:5174" 